version: "2.2"

services:

  jupyter-lab:
    image: jupyter/pyspark-notebook
    container_name: jupyter-lab
    hostname: jupyter-lab
    volumes: 
      - ./work:/home/jovyan
      - ./conf/apt/sources.list:/etc/apt/sources.list
    ports:
      - 8888:8888
      - 4040:4040
    environment: 
      - JUPYTER_ENABLE_LAB=yes

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    hostname: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: 
      - --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data:/var/lib/mysql

  mysql-adminer:
    image: adminer
    restart: always
    container_name: mysql-adminer
    hostname: mysql-adminer
    depends_on:
      - mysql-server
    environment: 
      - ADMINER_DEFAULT_SERVER=mysql-server
    ports:
      - "8088:8080"